version: '3.9'

services:
  todo-list-api:
    container_name: todo-list-api
    image: todo-list-api
    build:
      context: ../TodoListAPI
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  database:
    container_name: postgres-db
    image: postgres:16
    environment:
      POSTGRES_DB: todoList
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432